# Generated by Django 3.0.5 on 2020-09-04 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='crowled_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 4, 6, 17, 843424, tzinfo=utc)),
        ),
    ]
