# Generated by Django 3.0.5 on 2020-09-04 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200904_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='crowled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
