# Generated by Django 3.0.5 on 2020-09-04 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200904_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cookingstep',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='crowled_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 4, 23, 45, 40, 224766, tzinfo=utc)),
        ),
    ]
