# Generated by Django 3.0.5 on 2020-09-05 03:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200904_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingstep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='crowled_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 3, 25, 28, 738315, tzinfo=utc)),
        ),
    ]
